#!/usr/bin/env perl

use strict;
use warnings FATAL => qw ( all );

use Getopt::Long;

use Common::Config;
use Common::Messages;
use Common::Cluster;

my ( $prog_name, $usage, $signature, @msgs, $acctfile, $acctpath, $args,
     $count, $topath );

$prog_name = ( split "/", $0 )[-1];
$signature = &Common::Config::get_signature();

$acctpath = &Common::Cluster::accts_file;
$acctfile = File::Basename::basename( $acctpath );

$usage = qq (
Program $prog_name, January 2009.

Copies files or directories from all slave machines. Usage:

$prog_name from-path(s) to-path [ arguments ]

One or more from-paths specify the source files and a single target path 
the destination. Without the --combine argument, the destination is a 
directory in which subdirectories are made for each slave machine. With 
the --combine argument it is a single regular file. From-paths may be given 
as patterns in shell syntax, as for example using asterisks as wildcards,
preferable put in quotes (to avoid local shell expansion). The to-path
must be an absolute path name. Arguments:

      [ --combine ]   Creates a single local file - OPTIONAL (off) 
   [ --format key ]   Format of file(s) to combine - OPTIONAL (none)
    [ --recursive ]   Includes all sub-directories - OPTIONAL (off)
       [ --verify ]   Verify correct file sizes - OPTIONAL (off)
       [ --delete ]   Deletes to-path with --combine - OPTIONAL (on)

  [ --slaves name ]   Slave configuration file - OPTIONAL ($acctfile)
  [ --filter expr ]   Slave name filter expression - OPTIONAL (none)
 [ --timeout secs ]   Connection timeouts - OPTIONAL (5 seconds)
       [ --silent ]   Suppress progress messages - OPTIONAL (off)

Usage examples:

1\) $prog_name "Jobs/28-FEB-2009-20:18:29/outputs/*" Outputs --nocombine
2\) $prog_name "Jobs/28-FEB-2009-20:18:29/outputs/*" all.simscan \
           --combine --format simscan --verify --delete

Example 1 copies all outputs of a certain job to a local output directory,
where there will be subdirectories for each machine. Example 2 does the 
same, except the outputs are copied to a temporary directory, verified 
for correct copy, combined into a single file and then finally deleted.

ADVICE: before using $prog_name, use clu_dir to see if the expected 
        files are on the remote machines before copying them back.

$signature
);

&Common::Messages::print_usage_and_exit( $usage );

# >>>>>>>>>>>>>>>>>>>>>>>>> GET AND VALIDATE INPUT <<<<<<<<<<<<<<<<<<<<<<<<<

$args = &Common::Config::get_commandline(
    {
        "combine!" => 0,
        "format=s" => undef,
        "recursive!" => 0,
        "verify!" => 0,
        "delete!" => 1,
        "slaves=s" => $acctpath,
        "filter=s" => undef,
        "timeout=i" => undef,
        "silent!" => 0,
    });

if ( ($count = scalar @ARGV) <= 1 )
{
    @msgs = ( ["ERROR", qq (To-path is missing) ] );
}

if ( @msgs ) {
    &echo_messages( \@msgs );
    exit;
}

# >>>>>>>>>>>>>>>>>>>>>>>>>>>> PROCESS EACH NODE <<<<<<<<<<<<<<<<<<<<<<<<<<<

$topath = pop @ARGV;

&Common::Cluster::get_files(
    undef,
    {
        "from" => [ @ARGV ],
        "to" => $topath,
        "combine" => $args->combine,
        "format" => $args->format,
        "recursive" => $args->recursive,
        "verify" => $args->verify,
        "delete" => $args->delete,
        "acctfile" => $args->slaves,
        "acctexpr" => $args->filter,
        "timeout" => $args->timeout,
        "silent" => $args->silent,
        "nolog" => 1,
    });

&echo("\n");

__END__
