#!/usr/bin/env perl

use strict;
use warnings FATAL => qw ( all );

use Getopt::Long;

use Common::Config;
use Common::Messages;
use Common::Cluster;

my ( $prog_name, $usage, $signature, $args, $acctfile, $acctpath );

$prog_name = ( split "/", $0 )[-1];
$signature = &Common::Config::get_signature();

$acctpath = &Common::Cluster::accts_file;
$acctfile = File::Basename::basename( $acctpath );

$usage = qq (
Program $prog_name, February 2009.

Lists jobs and their status. Usage and command line arguments,

$prog_name [ job_ids ] [ arguments ]

 [ --program name ]   List jobs by program - OPTIONAL (all)
      [ --running ]   List running jobs - OPTIONAL (on)
      [ --stopped ]   List stopped jobs - OPTIONAL (on)
         [ --done ]   List completed jobs - OPTIONAL (off)
          [ --all ]   List all jobs - OPTIONAL (off)

  [ --slaves name ]   Slave configuration file - OPTIONAL ($acctfile)
  [ --filter expr ]   Slave name filter expression - OPTIONAL (none)
 [ --timeout secs ]   Connection timeouts - OPTIONAL (5 seconds)
       [ --silent ]   Suppress progress messages - OPTIONAL (on)

Job ids look like "18-FEB-2009-21:33:09" and are sub-directories in the 
Jobs directory on each slave ("clu_dir Jobs" will show these). All jobs
are shown by default, but the listing can be filtered by status and 
program. Usage examples:

1\) $prog_name --running --stopped
2\) $prog_name --program patscan

Example 1 lists running and stopped jobs only. Example 2 lists all 
patscan jobs, including the finished ones. 

$signature
);

&Common::Messages::print_usage_and_exit( $usage );

# >>>>>>>>>>>>>>>>>>>>>>>> GET AND VALIDATE INPUT <<<<<<<<<<<<<<<<<<<<<<<<

$args = &Common::Config::get_commandline(
    {
        "running!" => 0,
        "stopped!" => 0,
        "done!" => 0,
        "program=s" => undef,
        "all!" => 1,
        "slaves=s" => $acctpath,
        "filter=s" => undef,
        "timeout=s" => undef,
        "silent!" => 1,
    });

# >>>>>>>>>>>>>>>>>>>>>>>>>> PROCESS EACH NODE <<<<<<<<<<<<<<<<<<<<<<<<<<<

local $Common::Messages::silent = $args->silent;

&echo_bold( qq (\nJobs:\n) );

&Common::Cluster::slave_jobs(
    undef,
    {
        "jobids" => (join ",", @ARGV),
        "running" => $args->running,
        "stopped" => $args->stopped,
        "done" => $args->done,
        "program" => $args->program,
        "acctfile" => $args->slaves,
        "acctexpr" => $args->filter,
        "timeout" => $args->timeout,
        "format" => "ascii",
        "silent" => $args->silent,
    });

&echo_bold( qq (done\n\n) );

__END__
