#!/usr/bin/env perl

use strict;
use warnings FATAL => qw ( all );

use Getopt::Long;

use Common::Config;
use Common::Messages;
use Common::Cluster;
use Common::Tables;

my ( $prog_name, $usage, $signature, @msgs, $args, $acctfile, $acctpath, 
     $packages, %packages, @packages, $pkg, $routine, $sys_table, 
     $ana_table, $style );

$prog_name = ( split "/", $0 )[-1];
$signature = &Common::Config::get_signature();

$acctpath = &Common::Cluster::accts_file;
$acctfile = File::Basename::basename( $acctpath );

$style = { "align" => "right,left", "indent" => 3, "colsep" => "   " };

$sys_table = &Common::Cluster::system_packages();
$sys_table = Common::Tables->render_list( $sys_table, $style );

$ana_table = &Common::Cluster::analysis_packages();
$ana_table = Common::Tables->render_list( $ana_table, $style );

$usage = qq (
Program $prog_name, January 2009.

Installs software packages on the slave nodes. Packages are,

$sys_table

$ana_table

Arguments are,

  [ --slaves name ]   Slave configuration file - OPTIONAL ($acctfile)
  [ --filter expr ]   Slave name filter expression - OPTIONAL (none)
 [ --timeout secs ]   Connection timeouts - OPTIONAL (5 seconds)
        [ --force ]   Installs even if installed - OPTIONAL (off)
       [ --silent ]   Suppress progress messages - OPTIONAL (off)

Usage examples:

1\) $prog_name system patscan
2\) $prog_name simscan --slaves=simscan.nodes

Example 1 installs the system, then the simscan package on the 
machines given in the default configuration file ($acctfile). 
Example 2 installs the simscan package on the slaves given in the
'simscan.nodes' file. 

$signature
);

&Common::Messages::print_usage_and_exit( $usage );

# >>>>>>>>>>>>>>>>>>>>>>>>>>> GET ARGUMENTS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<

$args = &Common::Config::get_commandline(
    {
        "slaves=s" => $acctpath,
        "filter=s" => undef,
        "timeout=i" => 5,
        "force!" => 0,
        "silent!" => 0,
    });

# >>>>>>>>>>>>>>>>>>>>>>>>>> INSTALL PACKAGES <<<<<<<<<<<<<<<<<<<<<<<<<<<

&Common::Cluster::install_packages(
    {
        "packages" => \@ARGV,
        "acctfile" => $args->slaves,
        "acctexpr" => $args->filter,
        "timeout" => $args->timeout,
        "force" => $args->force,
        "silent" => $args->silent,
    });

&echo( "\n" );

__END__        
