#!/usr/bin/env perl

use strict;
use warnings FATAL => qw ( all );

my ( $usage, $emblfile, $nogaps, $line, $sid, $seq );

$usage = "
Usage:  embl2fasta EMBL-file [ -nogaps ]

The script converts a file of EMBL formatted entries to 
FASTA format. The 'OS' field is appended to the identifier,
or the 'DE' line(s) if there is no 'OS' field. 

";

if ( $#ARGV == -1 || $ARGV[0] =~ /-+help/i ) {
    print $usage;               
    exit (0);
}

$emblfile = $ARGV[0];
$nogaps = $ARGV[1];

open EMBL, $emblfile or die "Could not read-open $emblfile";

while ( defined ($line = <EMBL>) )
{
    if ( $line =~ /^\/\// )
    {
        if ( $sid )
        {
            print ">$sid\n$seq\n";
            $sid = $seq = "";
        }
    }
    elsif ( $line =~ /^ID\s+(\S+)/ )
    {
        $sid = $1;
    }
    elsif ( $line =~ /^\s{5,5}/ )
    {
        $line =~ s/\s//g;

        if ( $nogaps ) {
            $line =~ s/[^A-Za-z]//g;
        }
        
        $seq .= $line;
    }
}

close EMBL;
