#!/usr/bin/env perl

# -*- perl -*- 

# -----------------------------------------------------------------------
#
# Installs the perl modules named on the command line.
#
# Author: Niels Larsen, March 2009.
# 
# -----------------------------------------------------------------------

use strict;
use warnings FATAL => qw ( all );

use Common::Config;
use Common::Messages;

use Registry::Get;
use Install::Software;

my ( $prog_name, $signature, $usage, $args, $count, $msg );

# >>>>>>>>>>>>>>>>>>>>>>>>>> PRINT USAGE <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

$prog_name = ( split "/", $0 )[-1];
$signature = &Common::Config::get_signature();

$usage = qq (
Program $prog_name, March 2009.

Installs the perl modules named on the command line, or them all.
Switches:

     --all  Installs all uninstalled modules (off)
   --force  Installs even if already installed (off)
 --verbose  Prints more screen messages (off)
  --silent  Prints no screen messages (off)
    --list  List all available installs (off)

Examples: 

1\) $prog_name --list
2\) $prog_name --list --all
3\) $prog_name DB_File File-Type --force 
4\) $prog_name --all

Example 1 prints a table of the uninstalled modules. Example 2
prints the same table, but with all modules, installed or not. 
Example 3 installs two named modules, removing previous installs
if any. Example 4 installs all uninstalled modules. 

Author: $signature
);

&Common::Messages::print_usage_and_exit( $usage );

# >>>>>>>>>>>>>>>>>>>>>>>>>>> GET OPTIONS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

$args = &Common::Config::get_commandline(
    {
        "all!" => 0,
        "force!" => 0,
        "verbose!" => 0,
        "silent!" => 0,
        "list!" => 0,
        "debug!" => 0,
    });

if ( not @ARGV and not $args->all and not $args->list ) 
{
    $msg = "Please specify which module(s) to install";
    &echo_messages( [["ERROR", $msg ]] );
    exit 0;
}

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>> INSTALL <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

$count = &Install::Software::install_perl_modules(
    \@ARGV,
    {
        "all" => $args->all,
        "force" => $args->force,
        "verbose" => $args->verbose,
        "silent" => $args->silent,
        "list" => $args->list,
        "debug" => $args->debug,
        "print_header" => 1,
    });

exit if $args->silent;

if ( $count )
{
    &echo( "\n" );
}
else
{
    if ( $args->all ) {
        $msg = qq (All perl modules are installed);
    } elsif ( scalar @ARGV > 1 ) {
        $msg = qq (All of the given modules are installed);
    } else {
        $msg = qq (The @ARGV module is installed);
    }        

    &echo_messages( 
        [["OK", $msg ]],
        { "linewid" => 60, "linech" => "-" },
        );
}

__END__
