#!/usr/bin/env perl

# -*- perl -*- 

use strict;
use warnings FATAL => qw ( all );

use Getopt::Long;

use Common::Config;
use Common::Messages;

use Protein::Download;

my ( $prog_name, $signature, $usage );

$prog_name = ( split "/", $0 )[-1];
$signature = &Common::Config::get_signature();

# >>>>>>>>>>>>>>>>>>>>>>>> PRINT USAGE <<<<<<<<<<<<<<<<<<<<<<<<<<<

$usage = qq (
Program $prog_name, January 2006.

This program downloads various Protein sequence data sets, 
but only versions newer than the previous download. Command
line options are,

       --pfam    [ D = off; Pfam project (EBI/Wustl) ]
        --srp    [ D = off; SRP alignments (Texas) ]
      --tmrnp    [ D = off; tmRNP alignments (Texas) ]
    --uniprot    [ D = off; UniProt database (EBI/PIR) ]

        --all    [ D = off; all of the above ]

   --readonly    [ D = on; messages, but no download ]
 --noreadonly    [ D = off; starts the download ]

Messages are written to the console, if run from the 
console. Processing of the downloaded files is done by 
the program import_protein.

Author: $signature

);

print $usage and exit if not @ARGV;

# >>>>>>>>>>>>>>>>> GET ARGUMENTS <<<<<<<<<<<<<<<<<<<<<<

my ( $cl_args, $cl_readonly, $cl_headers );

# Defaults, 

$cl_readonly = 1;
$cl_headers = 1;

$cl_args->{"Pfam"} = 0;
$cl_args->{"SRP"} = 0;
$cl_args->{"tmRNP"} = 0;
$cl_args->{"UniProt"} = 0;
$cl_args->{"all"} = 0;

if ( not GetOptions(
                    "pfam!" => \$cl_args->{"Pfam"},
                    "srp!" => \$cl_args->{"SRP"},
                    "tmrnp!" => \$cl_args->{"tmRNP"},
                    "uniprot!" => \$cl_args->{"UniProt"},
                    "all" => \$cl_args->{"all"},

                    "headers!" => \$cl_headers,
                    "readonly!" => \$cl_readonly,
                    ) )
{
    exit;
}

if ( not grep { $_ } values %{ $cl_args } )
{
    &user_error( qq (Please specify at least one Protein to download.) );
    exit;
}

# >>>>>>>>>>>>>>>> DOWNLOAD RELEASE <<<<<<<<<<<<<<<<<<<<<

&echo( "\n" ) if $cl_headers;

if ( $cl_readonly ) {
    &echo_bold( "Download Proteins (readonly) : \n" ) if $cl_headers;
} else {
    &echo_bold( "Download Proteins: \n" ) if $cl_headers;
}

&Protein::Download::download_all( $cl_args, $cl_readonly );

&echo_bold( "Finished\n" ) if $cl_headers;

&echo( "\n" ) if $cl_headers;

# >>>>>>>>>>>>>>>> END OF MAIN PROGRAM <<<<<<<<<<<<<<<<<<<

__END__
