#!/usr/bin/env perl

# -*- perl -*- 

use strict;
use warnings FATAL => qw ( all );

use Getopt::Long;

use DNA::Import;
use Common::Messages;
use Common::Config;

my ( $prog_name, $signature, $usage );

$prog_name = ( split "/", $0 )[-1];
$signature = &Common::Config::get_signature();

# >>>>>>>>>>>>>>>>>>>>>>>> PRINT USAGE <<<<<<<<<<<<<<<<<<<<<<<<<<<

$usage = qq (
Program $prog_name, May 2004.

This program adds to the database the downloaded EMBL daily 
updates that are not in there already. Older versions of new
records are replaced. See also the 'import_embl_release' 
script. Command line options are,

  --[no]readonly   [ D = on; parsing, no database update ]
   --[no]restart   [ D = off; resumes disrupted loading ]
      --[no]keep   [ D = on; keep the flat-file sources ]

The default --readonly option will print screen messages and 
parse the files, but will not update the databases; this way
one can do a "test-run" to see if it is safe to start the real 
update. The --noreadonly option loads the data. 

The default --restart option loads only the files that have 
not yet been loaded. This is useful if something went wrong
during a load process that may take hours. 

Author: $signature

);

print STDERR $usage and exit if not @ARGV;

# >>>>>>>>>>>>>>>>>>>>>> GET ARGUMENTS <<<<<<<<<<<<<<<<<<<<<<<<

# Defaults, 

my $cl_readonly = 1;
my $cl_restart = 1;
my $cl_headers = 1;
my $cl_keep = 1;

if ( not &GetOptions (
                      "headers!" => \$cl_headers,
                      "restart!" => \$cl_restart,
                      "readonly!" => \$cl_readonly,
                      "keep!" => \$cl_keep,
                     ) )
{
    exit;
}

# >>>>>>>>>>>>>>>>>>>>>> BUILD UPDATES <<<<<<<<<<<<<<<<<<<<<<<<<

&echo( "\n" ) if $cl_headers;

if ( $cl_readonly ) {
    &echo_bold( "Importing EMBL updates (readonly) : \n" ) if $cl_headers;
} else {
    &echo_bold( "Importing EMBL updates : \n" ) if $cl_headers;
}

&DNA::Import::load_embl_updates( $cl_readonly, $cl_restart, $cl_keep );

&echo_bold( "Finished EMBL updates\n" ) if $cl_headers;
&echo( "\n" ) if $cl_headers;

# >>>>>>>>>>>>>>>>>>>> END OF MAIN PROGRAM <<<<<<<<<<<<<<<<<<<<

__END__
