#!/usr/bin/env perl

# -*- perl -*- 

use strict;
use warnings FATAL => qw ( all );

use Getopt::Long;

use DNA::Import;
use Common::Messages;
use Common::Config;

my ( $prog_name, $signature, $usage );

$prog_name = ( split "/", $0 )[-1];
$signature = &Common::Config::get_signature();

# >>>>>>>>>>>>>>>>>>>>>>>> PRINT USAGE <<<<<<<<<<<<<<<<<<<<<<<<<<<

$usage = qq (
Program $prog_name, June 2003.

This program builds a database from the downloaded EMBL full 
release records, making the annotations available for query. 
The script 'import_embl_updates' does the same for the daily 
update files. Command line options are,

  --[no]readonly   [ D = on; parsing, no database update ]
   --[no]restart   [ D = off; resumes disrupted loading ]
      --[no]keep   [ D = off; keep all flat-file sources ]

The default --readonly option will print screen messages and 
parse the files, but will not update the databases; this way
one can do a "test-run" to see if it is safe to start the real 
update. The --noreadonly option loads the data into the 
database after completely erasing the old database (if any). 

The default --restart option loads only the files that have 
not yet been loaded. This is useful if something went wrong
during a load process that may take many hours. 

Author: $signature

);

print STDERR $usage and exit if not @ARGV;

# >>>>>>>>>>>>>>>>>>>>>> GET ARGUMENTS <<<<<<<<<<<<<<<<<<<<<<<<

# Defaults, 

my $cl_readonly = 1;
my $cl_restart = 1;
my $cl_headers = 1;
my $cl_keep = 1;

if ( not &GetOptions (
                      "readonly!" => \$cl_readonly,
                      "restart!" => \$cl_restart,
                      "headers!" => \$cl_headers,
                      "keep!" => \$cl_keep,
                     ) )
{
    exit;
}

# >>>>>>>>>>>>>>>>>>> BUILD RELEASE <<<<<<<<<<<<<<<<<<<<<<<<<<<

&echo( "\n" ) if $cl_headers;

if ( $cl_readonly ) {
    &echo_bold( "Importing EMBL release (readonly) : \n" ) if $cl_headers;
} else {
    &echo_bold( "Importing EMBL release : \n" ) if $cl_headers;
}

&DNA::Import::load_embl_release( $cl_readonly, $cl_restart, $cl_keep );

&echo_bold( "Finished EMBL release\n" ) if $cl_headers;
&echo( "\n" ) if $cl_headers;

# >>>>>>>>>>>>>>>>>>>> END OF MAIN PROGRAM <<<<<<<<<<<<<<<<<<<<

__END__
